name: "Terraform"   #name of workflow

on: [push]    #event

jobs:
  terraform:
   runs-on: ubuntu-latest      #or unbuntu-latest
   steps:
    - name: Checkout #clones your code from ur repo into the virtual machines or Ec2 instance/stage ur 
            #workflow/job on your vm 
      uses: actions/checkout@v3
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    - name : terraform init
      run: terraform init    #run the following versions 
    - name: validate
      run : terraform validate
    - name: format
      run: terraform fmt -check
    - name : plan
      run: terraform plan